# Generated by Django 5.2.17 on 2026-09-13 14:22

import clinic.models.clinical
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substance', models.CharField(max_length=150)),
                ('reaction', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-threatening')], default='moderate', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'ordering': ['-is_active', 'substance'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Captured at write time so the trail survives the user being deleted.', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('login', 'Signed in'), ('login_failed', 'Failed sign-in'), ('logout', 'Signed out'), ('merge', 'Merged')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('clinical_examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_performed', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('next_visit_recommendation', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'In progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_treatments', models.TextField(blank=True)),
                ('last_dental_visit', models.DateField(blank=True, null=True)),
                ('oral_hygiene', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unknown', 'Not recorded')], default='unknown', max_length=20)),
                ('brushing_frequency', models.CharField(choices=[('twice_daily', 'Twice daily'), ('once_daily', 'Once daily'), ('irregular', 'Irregular'), ('unknown', 'Not recorded')], default='unknown', max_length=20)),
                ('flosses', models.BooleanField(blank=True, null=True)),
                ('tooth_sensitivity', models.BooleanField(blank=True, null=True)),
                ('tooth_sensitivity_notes', models.CharField(blank=True, max_length=255)),
                ('bleeding_gums', models.BooleanField(blank=True, null=True)),
                ('gum_disease', models.BooleanField(blank=True, null=True)),
                ('bruxism', models.BooleanField(blank=True, null=True)),
                ('orthodontic_history', models.BooleanField(blank=True, null=True)),
                ('orthodontic_notes', models.CharField(blank=True, max_length=255)),
                ('has_implants', models.BooleanField(blank=True, null=True)),
                ('has_crowns', models.BooleanField(blank=True, null=True)),
                ('has_bridges', models.BooleanField(blank=True, null=True)),
                ('has_dentures', models.BooleanField(blank=True, null=True)),
                ('root_canal_history', models.TextField(blank=True)),
                ('extractions', models.TextField(blank=True)),
                ('dental_material_reactions', models.TextField(blank=True, help_text='Reactions to latex, anaesthetic, metals and similar.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Dental history',
            },
        ),
        migrations.CreateModel(
            name='FamilyMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(help_text='Mother, father, sibling, and so on.', max_length=100)),
                ('condition', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Family medical history',
                'ordering': ['relationship', 'condition'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('admitted_date', models.DateField(blank=True, null=True)),
                ('discharged_date', models.DateField(blank=True, null=True)),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-admitted_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(max_length=200)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('managed', 'Managed'), ('resolved', 'Resolved'), ('unknown', 'Not recorded')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-diagnosed_date', 'condition'],
            },
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smoking_status', models.CharField(choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('current', 'Current smoker'), ('unknown', 'Not recorded')], default='unknown', max_length=20)),
                ('alcohol_use', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('former', 'Former'), ('unknown', 'Not recorded')], default='unknown', max_length=20)),
                ('pregnancy_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('not_pregnant', 'Not pregnant'), ('pregnant', 'Pregnant'), ('breastfeeding', 'Breastfeeding'), ('unknown', 'Not recorded')], default='not_applicable', max_length=20)),
                ('other_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PastSurgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.CharField(max_length=200)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, help_text='Used when the exact date is unknown.', max_length=10)),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Past surgeries',
                'ordering': ['-surgery_date', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('patient_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Falls back to first + last name when left empty.', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email_normalized', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], max_length=10)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('preferred_language', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('xray', 'X-ray'), ('scan', 'Scan'), ('report', 'Report'), ('consent', 'Consent form'), ('photo', 'Clinical photo'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=clinic.models.clinical.patient_document_path)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'medication_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('prescribed_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-prescribed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('instructions', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('dentist', 'Dentist'), ('admin', 'Administrator'), ('assistant', 'Dental Assistant'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tooth_number', models.CharField(blank=True, help_text='FDI notation, e.g. 36. Blank if not tooth-specific.', max_length=20)),
                ('surfaces', models.CharField(blank=True, help_text='Tooth surfaces involved, e.g. MOD.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('performed_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-performed_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='match_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Patient ids a website booking could plausibly belong to, when more than one matched.'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='match_status',
            field=models.CharField(choices=[('linked', 'Linked to existing patient'), ('created', 'New patient created'), ('ambiguous', 'Needs staff review'), ('unmatched', 'Not linked')], default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('clinic', 'Clinic'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='clinic.appointment'),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinic.dentist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Set when this record was merged into another; kept for audit trail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='pastsurgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='familymedicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='dentalhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_history', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Set when the action concerned a specific patient, so a per-patient access history can be shown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.patient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='clinic_appo_appoint_e3a153_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='clinic_appo_patient_616a63_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('cancelled', 'no_show')), _negated=True), fields=('appointment_date', 'appointment_time'), name='unique_active_appointment_slot'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clinic.clinicalvisit'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinic.dentist'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinic.clinicalvisit'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.prescription'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='clinic.clinicalvisit'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='clinic_pati_last_na_fe6026_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='clinic_pati_is_acti_648c42_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalvisit',
            index=models.Index(fields=['patient', '-visit_date'], name='clinic_clin_patient_f6439c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='clinic_audi_timesta_2db4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='clinic_audi_model_n_efe777_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['patient', '-timestamp'], name='clinic_audi_patient_13d11b_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-prescribed_date'], name='clinic_pres_patient_b34f22_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['patient', '-performed_date'], name='clinic_trea_patient_720221_idx'),
        ),
    ]
