# Generated by Django 5.2.17 on 2026-09-17 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_backfill_patients_and_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('edited', 'Edited'), ('checked_in', 'Checked in'), ('arrival_corrected', 'Arrival time corrected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'Marked no-show'), ('slot_override', 'Slot conflict overridden')], max_length=30)),
                ('changed_by_name', models.CharField(blank=True, help_text='Captured at write time so the timeline survives the user being deleted.', max_length=150)),
                ('old_date', models.DateField(blank=True, null=True)),
                ('old_time', models.TimeField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_time', models.TimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Appointment history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('booking_received', 'Booking received'), ('confirmation', 'Confirmation'), ('reschedule', 'Reschedule'), ('cancellation', 'Cancellation'), ('reminder', 'Reminder')], max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('dedupe_key', models.CharField(help_text='Unique per appointment; repeat sends for the same event collapse onto one row.', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time'], 'permissions': [('override_appointment_slot', 'Can book over an existing appointment (slot conflict override)')]},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status__in', ('cancelled', 'no_show')), _negated=True), models.Q(('source__in', ('walk_in',)), _negated=True), ('slot_override', False)), fields=('appointment_date', 'appointment_time'), name='unique_active_appointment_slot'),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clinic.appointment'),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentnotification',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinic.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(fields=['appointment', '-created_at'], name='clinic_appo_appoint_7df9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentnotification',
            index=models.Index(fields=['status', '-created_at'], name='clinic_appo_status_fb73ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentnotification',
            constraint=models.UniqueConstraint(fields=('appointment', 'dedupe_key'), name='unique_appointment_notification_event'),
        ),
    ]
