# Generated by Django 5.2.17 on 2026-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_backfill_appointment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('booking_received', 'Booking received'), ('confirmation', 'Confirmation'), ('reschedule', 'Reschedule'), ('cancellation', 'Cancellation'), ('request_declined', 'Request could not be confirmed'), ('reminder', 'Reminder')], max_length=30),
        ),
    ]
