# Generated by Django 5.2.17 on 2026-09-17 17:11

"""Record the ClinicSettings field defaults that came with the upstream
merge.

The upstream branch changed the placeholder defaults to the client's real
details but shipped only the data migrations that update the existing row, not
the field-state change itself. Django tracks `default` in migration state, so
without this the app has a permanently pending migration and
`makemigrations --check` fails in CI.

No effect on existing data: defaults apply only to rows created from here on,
and the live row was already updated by 0008/0009.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_rename_clinic_and_new_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='address',
            field=models.CharField(default='No. 23, SS Towers, Kurumbapalayam, Sathy road, Sarkarsamakulam PO, Coimbatore 641107, Tamilnadu', max_length=300),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default="Dr. Belin's Dentistry", max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='email',
            field=models.EmailField(blank=True, default='drbelinroshia@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='google_maps_url',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/1sA41VZLgnzXNse86', help_text='Link to open the clinic location in Google Maps.'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='phone',
            field=models.CharField(default='+91 88707 74432', max_length=30),
        ),
    ]
