# Generated by Django 5.2.17 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_update_clinic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='email',
            field=models.EmailField(blank=True, default='belindentistry@gmail.com', max_length=254),
        ),
    ]
