# Generated by Django 5.2.17 on 2026-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_clinic_map_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='name',
            field=models.CharField(default='Dr. Belin Roshia', max_length=150),
        ),
    ]
