# Generated by Django 5.2.17 on 2026-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_dentist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
